version: '3'
services:
  db-postgres:
    image: postgres:9.6.20
    container_name: postgres
    restart: unless-stopped
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - "45432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db-oracle:
    image: wnameless/oracle-xe-11g-r2:18.04-apex
    container_name: oracle
    restart: unless-stopped
    volumes:
    - oracle:/u01/app/oracle
    ports:
    - "41521:1521"
    - "48080:8080"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
volumes:
  oracle:
  postgres: